### ISSUE TITLE
[Enhancement] provide xinetd release for Alpine Linux / Docker

### ISSUE THREAD

**Issue by davidpelfree** [openSUSE/xinetd#17]
Alpine Linux become very popular as a base layer of Docker images.

I have a legacy application, based on XINETD. 

I would like to run it inside Docker container, based on Alpine Linux, but I don't know how to create APK package, nor how to compile with ulibc (Alpine's glibc alternative).

Can you assist here please?

**Comment by vapier** [comment]
we don't provide distro packages.  you probably want to ask Alpine Linux to create one.  i assume they have a website/mailing list/forums you can ask on :).

feel free to link here if/once they do!
