### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by ltworf** [openSUSE/xinetd#2]
Lintian found some more spelling mistakes.

I: xinetd: spelling-error-in-manpage usr/share/man/man3/Sprint.3.gz overriden overridden
I: xinetd: spelling-error-in-manpage usr/share/man/man3/Sprint.3.gz overriden overridden
I: xinetd: spelling-error-in-manpage usr/share/man/man3/Sprint.3.gz occured occurred
I: xinetd: spelling-error-in-manpage usr/share/man/man3/strparse.3.gz occured occurred

It also complains about this
```
src/parsers.c:          "attribute %s expects at least 1 value and none were given.",
```

Saying that it should be `none was`. But my English isn't so good to decide on this :D

**Comment by ltworf** [comment]
On second thought, if I had commit access, I could fix this stuff by myself and it could go in the next release.

**Comment by plusky** [comment]
You don't need commit access to send merge request.

**Comment by scarabeusiv** [comment]
@ltworf Also if you want commit access I can give it to you for sure as I do not think it would be easier for the Debian patches to trickle in... :)
