### ISSUE TITLE
Enable building against alternative RPC implementations

### ISSUE THREAD

**Issue by ismaell** [openSUSE/xinetd#27]
The implementation may be provided by the libc or some other library instead of libtirpc.

**Comment by davide125** [comment]
This isn't working quite right. At least on Fedora, I have to explicitly pass `CFLAGS='-I/usr/include/tirpc' LDFLAGS="-ltirpc"` to `./configure` or it won't pick libtirpc up properly.

**Comment by vapier** [comment]
hard to explain w/out a config.log

**Comment by davide125** [comment]
Here you go: https://gist.github.com/davide125/1f405dc032796043950cce1784601a73

Looking at `libtirpc-devel`, it puts its includes under `/usr/include/tirpc` (e.g. `/usr/include/tirpc/rpc/rpc.h`).

**Comment by vapier** [comment]
right, that's why we probe the settings via pkg-config:
`            [*], [PKG_CHECK_MODULES([RPC], ["$rpc_impl"], [], [continue])])`

looks like the problem is here:
```
        AS_CASE(["$rpc_impl"],
            [libc], [],
            [no], [break],
            [*], [PKG_CHECK_MODULES([RPC], ["$rpc_impl"], [], [continue])])
        have_rpc=maybe
        AC_CHECK_HEADERS([rpc/rpc.h],, [have_rpc=no; break])
```

the code needs to temporarily append `$RPC_FLAGS` to `$CPPFLAGS` before calling `AC_CHECK_HEADERS`, and then restore the value.
