### ISSUE TITLE
.3 manpages installed

### ISSUE THREAD

**Issue by ltworf** [openSUSE/xinetd#3]
The make install installs some manpages about C functions. Since no .h or library is installed, I don't think they should be installed.

I made a patch to not install them.

```
--- a/Makefile.am
+++ b/Makefile.am
@@ -31,19 +31,10 @@ xinetconf_DATA = \
 
 man_MANS = \
        man/itox.8 \
-       man/m_env.3 \
-       man/pset.3 \
-       man/psi.3 \
-       man/sio.3 \
-       man/Sprint.3 \
-       man/strparse.3 \
-       man/strprint.3 \
-       man/strutil.3 \
        man/xconv.pl.8 \
        man/xinetd.conf.5 \
        man/xinetd.log.5 \
-       man/xinetd.8 \
-       man/xlog.3
+       man/xinetd.8
 
 AM_LDFLAGS = $(LDFLAGS) $(HARDEN_LDFLAGS)
 AM_CFLAGS = $(CFLAGS) $(HARDEN_CFLAGS)
```

**Comment by scarabeusiv** [comment]
Feel free to create pullrequest with this, also as it is ti should be mentioned as extra content so it is present in the distribution tarball on release.

**Comment by ltworf** [comment]
This is a patch for the issue.

Unfortunately gh doesn't support .patch files -_-

[0001-Do-not-install-manpages-of-C-functions.txt](https://github.com/openSUSE/xinetd/files/1191529/0001-Do-not-install-manpages-of-C-functions.txt)

**Comment by scarabeusiv** [comment]
Merged.
